version: "3.6"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATADIR}/portainer:/data 
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAINNAME}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=mydnschallenge"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.middlewares=portainer-auth"
      - "traefik.http.middlewares.portainer-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.portainer-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.portainer-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
